export enum NotificationType {
  REGISTRATION = 'REGISTRATION',
  PAYMENT_REMINDER = 'PAYMENT_REMINDER',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  ENROLLMENT_APPROVED = 'ENROLLMENT_APPROVED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  GENERAL = 'GENERAL',
}
